language:
  - python
  - node_js
python:
  - 2.7
node_js:
  - "0.10"
notifications:
  irc: irc.freenode.org#greenfinity
before_install:
  - sudo apt-get install libevent-dev
install:
  - pip install -e '.[test]' --use-mirrors
  - npm install .
  - mkdir bower_components
  - export PATH="$PWD/node_modules/.bin:$PATH"
  - export DISPLAY=:99.0
  - grunt install
before_script:
  - echo 'Starting xvfb for FF...'
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - echo 'Done.'
script:
  - nosetests --with-coverage --cover-package=ubikdb --cover-min-percentage=0
  - grunt test