language:
  - python
  - node_js
python:
  - 2.7
node_js:
  - "0.10"
notifications:
  irc: irc.freenode.org#greenfinity
install:
#  - pip install -e '.[testing]' --use-mirrors
  - npm install
  - mkdir bower_components
  - grunt install
  - export PATH="$PWD/node_modules/.bin:$PATH"
  - export DISPLAY=:99.0
before_script:
  - echo 'Starting xvfb for FF...'
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - echo 'Done.'
script:
#  - nosetests --with-coverage --cover-package=ubikdb --cover-min-percentage=0
  - grunt karma:unit