language:
  - python
  - node_js
python:
  - 2.7
node_js:
  - "0.10"
notifications:
  irc: irc.freenode.org#greenfinity
before_install:
  - sudo apt-get install libevent-dev
install:
  - pip install -e '.[test]' --use-mirrors
  - mkdir bower_components
  - npm install .
script:
  - nosetests --with-coverage --cover-package=ubikdb --cover-min-percentage=0
  - grunt test